# Generated by Django 5.2.5 on 2025-08-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_father', models.CharField(max_length=100)),
                ('joindate', models.DateField()),
                ('stu_class', models.CharField(max_length=20, unique=True)),
                ('fees', models.PositiveIntegerField()),
            ],
        ),
    ]
