# Generated by Django 5.2.5 on 2025-08-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routedetail',
            options={'verbose_name': 'RouteDetail', 'verbose_name_plural': 'RouteDetails'},
        ),
    ]
